### PR TITLE
[IMPROVE] RTL support

### PR DESCRIPTION
**Pull request by darkhorse-coder**
## Description
- added `isRtl` props to `BottomFabBar`

### CODE REVIEW

**Comment by Jm-Zion** [comment]
Hi ✋ 

Thank you for the contribution, i'll take a look by the end of the week hopefully ! :)

**Comment by Jm-Zion** [comment]
Hi ✋ 

Can you check this behavior ? Rotation doesn't seem to work well.

https://user-images.githubusercontent.com/19466709/163047533-7c367a43-e68f-4096-96bd-0a0fe0c996b2.mp4

**Comment by darkhorse-coder** [comment]
Hi, I will check again, @Jm-Zion

**Comment by darkhorse-coder** [comment]
Hi @Jm-Zion 
Fixed issues, Could you please check again? Please check this video.


https://user-images.githubusercontent.com/32187178/163698335-96d197ac-7cbf-49c1-93b4-3204ea77e7fd.mp4

Thanks

**Comment by darkhorse-coder** [comment]
Hi 👋  @Jm-Zion, Could you please check this PR? Thanks.

**Comment by Jm-Zion** [comment]
Thank you, looks good to me, can you fix issue provided by CodeFactor ?

**Comment by Jm-Zion** [comment]
I fixed eslint errors on master

**Comment by darkhorse-coder** [comment]
Hi @Jm-Zion All things passed, please check. Thank you.

**Comment by Jm-Zion** [comment]
It's been merged, thank you for the contribution 🙏

**Pull request closed without merging**
